FROM golang:1.22.4-alpine AS builder

WORKDIR /api
COPY go.mod go.sum ./

RUN go mod download && go mod verify
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o ./gin-server ./cmd/gin

FROM alpine

COPY --from=builder /api/gin-server .
EXPOSE 8080
ENTRYPOINT [ "./gin-server" ]

